### PR TITLE
Add a QT GUI

### PR DESCRIPTION
**Pull request by chrisveilleux**
#### Description
Add the QML and hooks into the GUI framework necessary to display timers on a Mark II

#### Type of PR
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
_Either delete those that do not apply, or add an x between the square brackets like so: `- [x]`_
- [ ] Bugfix
- [x] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

#### Testing
Load onto a device using the QT GUI framework and set timers.

#### Documentation
Documentation on the skill already exists.

### CODE REVIEW

**Comment by JarbasAl** [comment]
why is this mark2 only? doesnt it work in all GUIs?

the enclosure check is dumb, if anything check for mark1 which only supports the default. Why does everyone get the mark1 render which only works in 1 device, but the GUI that works everywhere checks for mark2?

GUI can even be remote and connected to a mark1, so i would argue the enclosure check is non sense, might aswel call both functions since they don't conflict i think. In the end the mark1 needs to be abstracted away in a next step, or you will end up with lots of kludges all over the place

**Comment by forslund** [comment]
Agree with Jarbas, just publish the events and if a gui is connected it'd be shown if no gui is connected it won't. I don't think it's needed but there is also the possibility to use `self.gui.connected` to verify. But if might be as well to always populate the gui so the page is shown if a gui is connected.

**Comment by krisgesling** [comment]
_Note to anyone following: this PR got merged unintentionally._

This is looking good. 

I think it makes sense to generalize the GUI to all platforms.

I also wonder if we can have a single `render_timer` function that either calls `render_qt_gui`, or refactor a little to something like:
```Python
def render_timer(self, idx, seconds, timer=None):
    self.render_simple_timer(idx, seconds) # existing render code
    if self.gui.connected:
        self.render_gui_timer(...)
```

In terms of the countdown logic, I'm still of the opinion that this would be better handled on the qml side. The inconsistent time changes are very noticeable. 

Not for this iteration:
- With the progress bar, for short timers (eg 10 seconds) the bar will jump forward on each second. We could animate this to be a smooth fill. 
- Still haven't figured out the best way to handle multiple timers reusing the same qml page rather than duplicating it...

**Comment by AIIX** [comment]
>     * Still haven't figured out the best way to handle multiple timers reusing the same qml page rather than duplicating it...

One can send the timer data as a model instead of single timer data as in:

Instead of:
```
  self.gui['timer_color'] = BACKGROUND_COLORS[color_idx]
  self.gui['timer_name'] = timer_name
  self.gui['percent_elapsed'] = percent_elapsed
  self.gui['time_remaining'] = remaining_time_display
```

One could use a model like below and append a new timer to it once a new timer is created:
``` 
self.gui['timer_data'] = [{"timer_color": BACKGROUND_COLORS[color_idx], "timer_name": timer_name, "percent_elaspsed": percent_elapsed, "time_remaining": remaining_time_display, "timer_id": 1}, {"timer_color": BACKGROUND_COLORS[color_idx], "timer_name": timer_name, "percent_elaspsed": percent_elapsed, "time_remaining": remaining_time_display, "timer_id": 2}, {"timer_color": BACKGROUND_COLORS[color_idx], "timer_name": timer_name, "percent_elaspsed": percent_elapsed, "time_remaining": remaining_time_display, "timer_id": 3}] 
```

And then use a listview in QML to use the same qml of the timer to replicate itself based on the model data.

**Comment by AIIX** [comment]
> In terms of the countdown logic, I'm still of the opinion that this would be better handled on the qml side. The inconsistent time changes are very noticeable.

it seems gui api core side does not implement "mycroft.session.list.update" https://github.com/MycroftAI/mycroft-gui/blob/master/transportProtocol.md#updates-item-values-starting-at-the-given-position-as-many-items-as-there-are-in-the-array which might be why there is inconsistent time changes, as one might just be reinserting a new model instead of updating values of an existing model

**Pull request merged**
