### PR TITLE
Major update of Timer Skill

### PR DESCRIPTION
**Pull request by krisgesling**
Major update of Timer Skill based on VUI release document including:
- lots of new dialog
- improved support of named timers
- improved handling of ordinals for timers with same duration, or if no duplicates - of all timers.
- improved handling selecting timers from list

### CODE REVIEW

**Comment by forslund** [comment]
All my tests indicate that this is still working nicely. I wonder if the start timer intent definition should be more strict? basically anything including the word "timer" not matching other things will trigger the set timer intent.

**Comment by krisgesling** [comment]
Yeah it's hard, the suggestion was to support utterances that don't include verbs (like "set", "start" etc) So there's a whole range of utterances like:
- "10 minute timer"
- "timer for pasta"
- or even just "timer"

This seemed like the best option, and should be very easy to over match with Padatious or even longer Adapt intents.

**Comment by krisgesling** [comment]
Actually hold off on merging this until Kale can give it a solid test run.

**Comment by krisgesling** [comment]
QA testing hasn't found any problematic utterances, so merging this.

**Pull request merged**
