### PR TITLE
Changes for Basque language

### PR DESCRIPTION
**Pull request by e-gor**
Changes for Basque language
===========================

#### Description

These changes, along with those sent to other repos, make Mycroft work in Basque language.

Made by Elhuyar, Talaios and Skura

#### Type of PR

Feature implementation

### CODE REVIEW

**Comment by krisgesling** [comment]
Chris is doing a big refactor of this Skill at the moment, so leaving this for him.

CLA has been received though.

**Comment by chrisveilleux** [comment]
The names of the dialog and vocabulary files were altered as part of a major refactor of this skill.  Please see the latest naming conventions in the 21.02 branch.

**Comment by e-gor** [comment]
Refactoring of dialog and vocab files done.

**Comment by krisgesling** [comment]
Thanks Igor, looks all correct to me.

@chrisveilleux looks like you missed "dashing" the `lang/intents/some-files.intent`. This PR uses what you have in en-us.

**Review by krisgesling — APPROVED** [review]

**Pull request merged**
